spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:gl9OPI0MsT-MrW8Zo2uVPC5jy-0Y5GJlQxpDq0TJTIPklXfT@45279f47-f8e5-47e4-8d46-7e86ef536553.asia-southeast1.firestore.goog:443/db-nexashopping?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
    

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

